{
    "data": [
        {
            "test_name": "python.IsisPowder.ISISPowderPearlTest.ISISPowderPearlTest",
            "latest_failed_build": "1951",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 8,
            "past_outcome": {
                "build_keys": [
                    "1961",
                    "1960",
                    "1959",
                    "1958",
                    "1957",
                    "1956",
                    "1955",
                    "1954",
                    "1953",
                    "1952",
                    "1951",
                    "1950",
                    "1949",
                    "1948",
                    "1947",
                    "1946",
                    "1945",
                    "1944",
                    "1943",
                    "1942",
                    "1941",
                    "1940",
                    "1939",
                    "1938",
                    "1937",
                    "1936",
                    "1935",
                    "1934",
                    "1933",
                    "1932"
                ],
                "past_outcome_list": [
                    "None",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Failed",
                    "Failed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Failed",
                    "Passed",
                    "Failed",
                    "Failed",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.IsisPowder.ISISPowderPearlTest.ISISPowderPearlTest",
                "build": "1951",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "6.98",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.6.20230309.0726.dev195\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nNo config file was specified. If a configuration file  was meant to be used the path to the file is set with the &#x27;config_file&#x27; parameter.\n\nReplacing parameter: &#x27;create_cal_rebin_1_params&#x27; which was previously set to: &#x27;100,-0.0006,19950&#x27; with new value: &#x27;20300,-0.0006,39990&#x27;\nReplacing parameter: &#x27;monitor_lambda_crop_range&#x27; which was previously set to: &#x27;(0.03, 6.0)&#x27; with new value: &#x27;(5.9, 12.0)&#x27;\nReplacing parameter: &#x27;monitor_integration_range&#x27; which was previously set to: &#x27;(0.6, 5.0)&#x27; with new value: &#x27;(6, 10)&#x27;\nReplacing parameter: &#x27;raw_data_tof_cropping&#x27; which was previously set to: &#x27;(0, 19995)&#x27; with new value: &#x27;(20280, 39000)&#x27;\nReplacing parameter: &#x27;vanadium_tof_cropping&#x27; which was previously set to: &#x27;(1400, 19990)&#x27; with new value: &#x27;(20295, 39000)&#x27;\nReplacing parameter: &#x27;focused_cropping_values&#x27; which was previously set to: &#x27;[(1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900)]&#x27; with new value: &#x27;[(20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830)]&#x27;\nReplacing parameter: &#x27;custom_focused_cropping_values&#x27; which was previously set to: &#x27;(1500, 19990)&#x27; with new value: &#x27;(20300, 38830)&#x27;\nReplacing parameter: &#x27;spline_coefficient&#x27; which was previously set to: &#x27;60&#x27; with new value: &#x27;5&#x27;\nE\n======================================================================\nERROR: test_long_mode_on (ISISPowderPearlTest.ISISPowderPearlTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/test/ISISPowderPearlTest.py&quot;, line 41, in test_long_mode_on\n    inst_obj.focus(run_number=999)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/pearl.py&quot;, line 41, in focus\n    return self._focus(\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/abstract_inst.py&quot;, line 94, in _focus\n    return self._output_focused_runs(focused_runs, run_number_string)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/abstract_inst.py&quot;, line 97, in _output_focused_runs\n    run_details = self._get_run_details(run_number_string)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/pearl.py&quot;, line 108, in _get_run_details\n    tt_mode_string = self._inst_settings.tt_mode\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/routines/instrument_settings.py&quot;, line 62, in __getattr__\n    self._raise_user_param_missing_error(known_param)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/routines/instrument_settings.py&quot;, line 124, in _raise_user_param_missing_error\n    raise AttributeError(err_text)\nAttributeError: The parameter with name: &#x27;tt_mode&#x27; is required but was not set or passed.\nAcceptable values for this parameter are: all, tt35, tt70, tt88, custom\n\n----------------------------------------------------------------------\nRan 1 test in 0.007s\n\nFAILED (errors=1)\n\n          Start 1891: MDAlgorithmsTest_LoadDNSSCDTest\n"
            }
        },
        {
            "test_name": "PythonSANSQt5.beam_centre_presenter_test.beam_centre_presenter_test",
            "latest_failed_build": "1948",
            "agent_name": "Mac",
            "last_failed_outcome": "Flake",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "1961",
                    "1960",
                    "1959",
                    "1958",
                    "1957",
                    "1956",
                    "1955",
                    "1954",
                    "1953",
                    "1952",
                    "1951",
                    "1950",
                    "1949",
                    "1948",
                    "1947",
                    "1946",
                    "1945",
                    "1944",
                    "1943",
                    "1942",
                    "1941",
                    "1940",
                    "1939",
                    "1938",
                    "1937",
                    "1936",
                    "1935",
                    "1934",
                    "1933",
                    "1932"
                ],
                "past_outcome_list": [
                    "None",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Flake",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "PythonSANSQt5.beam_centre_presenter_test.beam_centre_presenter_test",
                "build": "1948",
                "agent_name": "Mac",
                "trial": 1,
                "outcome": "Failed",
                "test_time": "11.85",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.6.20230309.0726.dev194\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\n.F.......SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.......\n======================================================================\nFAIL: test_copies_into_internal_model (beam_centre_presenter_test.BeamCentrePresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/SANS/gui_logic/beam_centre_presenter_test.py&quot;, line 150, in test_copies_into_internal_model\n    self.assertEqual(getattr(mocked_external_model, attr), getattr(self.presenter._beam_centre_model, attr))\nAssertionError: 0.0 != 1.85\n\n----------------------------------------------------------------------\nRan 17 tests in 3.920s\n\nFAILED (failures=1)\n\n          Start 2600: PythonSANSQt5.beam_centre_presenter_test.beam_centre_presenter_test\n"
            }
        }
    ]
}