{
    "data": [
        {
            "test_name": "python.EngineeringDiffraction.test_presenter.test_presenter",
            "latest_failed_build": "2684",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "2686",
                    "2685",
                    "2684",
                    "2683",
                    "2682",
                    "2681",
                    "2680",
                    "2679",
                    "2678",
                    "2677",
                    "2676",
                    "2675",
                    "2674",
                    "2673",
                    "2672",
                    "2671",
                    "2670",
                    "2669",
                    "2668",
                    "2667",
                    "2666",
                    "2665",
                    "2664",
                    "2663",
                    "2662",
                    "2661",
                    "2660",
                    "2659",
                    "2658",
                    "2657"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.EngineeringDiffraction.test_presenter.test_presenter",
                "build": "2684",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "10.21",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.6.20230524.1549.dev3\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\n..Python-[Notice] Starting to fit workspace ws1\nPython-[Notice] Starting to fit workspace ws2\nPython-[Notice] Serial fitting finished.\n..Python-[Notice] Starting to fit workspace ws1\nPython-[Notice] Starting to fit workspace ws2\nPython-[Notice] Sequential fitting finished.\n.....Python-[Warning] No plotted data to fit to\nFPython-[Warning] No plotted data to fit to\nFPython-[Warning] No plotted data to fit to\nFPython-[Warning] No plotted data to fit to\nF...\n======================================================================\nFAIL: test_fit_all_started_notified_sequential (test_presenter.FittingPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/test/test_presenter.py&quot;, line 146, in test_fit_all_started_notified_sequential\n    self.presenter.plot_widget.fit_all_started_notifier.notify_subscribers.assert_called_once_with((True))\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 924, in assert_called_once_with\n    raise AssertionError(msg)\nAssertionError: Expected &#x27;mock&#x27; to be called once. Called 0 times.\n\n======================================================================\nFAIL: test_fit_all_started_notified_serial (test_presenter.FittingPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/test/test_presenter.py&quot;, line 151, in test_fit_all_started_notified_serial\n    self.presenter.plot_widget.fit_all_started_notifier.notify_subscribers.assert_called_once_with((False))\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 924, in assert_called_once_with\n    raise AssertionError(msg)\nAssertionError: Expected &#x27;mock&#x27; to be called once. Called 0 times.\n\n======================================================================\nFAIL: test_fit_all_started_sequential (test_presenter.FittingPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/test/test_presenter.py&quot;, line 163, in test_fit_all_started_sequential\n    self.presenter.disable_view.assert_called_once_with(fit_all=True)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 924, in assert_called_once_with\n    raise AssertionError(msg)\nAssertionError: Expected &#x27;mock&#x27; to be called once. Called 0 times.\n\n======================================================================\nFAIL: test_fit_all_started_serial (test_presenter.FittingPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/test/test_presenter.py&quot;, line 176, in test_fit_all_started_serial\n    self.presenter.disable_view.assert_called_once_with(fit_all=True)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 924, in assert_called_once_with\n    raise AssertionError(msg)\nAssertionError: Expected &#x27;mock&#x27; to be called once. Called 0 times.\n\n----------------------------------------------------------------------\nRan 16 tests in 0.974s\n\nFAILED (failures=4)\n\n          Start 2014: mantidqt_qt5.test_async.test_async\n"
            }
        }
    ]
}