{
    "data": [
        {
            "test_name": "python.scripts.AbinsCalculateSPowderTest.AbinsCalculateSPowderTest",
            "latest_failed_build": "4222",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "4233",
                    "4232",
                    "4231",
                    "4230",
                    "4229",
                    "4228",
                    "4227",
                    "4226",
                    "4225",
                    "4224",
                    "4223",
                    "4222",
                    "4221",
                    "4220",
                    "4219",
                    "4218",
                    "4217",
                    "4216",
                    "4215",
                    "4214",
                    "4213",
                    "4212",
                    "4211",
                    "4210",
                    "4209",
                    "4208",
                    "4207",
                    "4206",
                    "4205",
                    "4204"
                ],
                "past_outcome_list": [
                    "None",
                    "None",
                    "None",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsCalculateSPowderTest.AbinsCalculateSPowderTest",
                "build": "4222",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "10.62",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.6.20230602.1033.dev183\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nPython-[Notice] Data not found in cache. Structure factors need to be calculated.\nPython-[Notice] Warning: No group Powder in hdf file. Data has to be calculated.\nPython-[Notice] Tensor data for analytic powder averaging has been calculated.\n.Python-[Notice] Data not found in cache. Structure factors need to be calculated.\nPython-[Notice] Warning: [Errno 2] Unable to open file (unable to open file: name = &#x27;Si2-sc_CalculateSPowder.hdf5&#x27;, errno = 2, error message = &#x27;No such file or directory&#x27;, flags = 0, o_flags = 0) Data has to be calculated.\nPython-[Notice] Tensor data for analytic powder averaging has been calculated.\nFPython-[Notice] Data not found in cache. Structure factors need to be calculated.\nPython-[Notice] Warning: [Errno 2] Unable to open file (unable to open file: name = &#x27;Si2-sc_CalculateSPowder.hdf5&#x27;, errno = 2, error message = &#x27;No such file or directory&#x27;, flags = 0, o_flags = 0) Data has to be calculated.\nPython-[Notice] Tensor data for analytic powder averaging has been calculated.\n.Python-[Notice] Using default setting &quot;A&quot; for instrument &quot;MARI&quot;\nPython-[Notice] Using default chopper frequency for instrument MARI: 400 Hz\nPython-[Notice] Data not found in cache. Structure factors need to be calculated.\nPython-[Notice] Warning: [Errno 2] Unable to open file (unable to open file: name = &#x27;Si2-sc_CalculateSPowder.hdf5&#x27;, errno = 2, error message = &#x27;No such file or directory&#x27;, flags = 0, o_flags = 0) Data has to be calculated.\nPython-[Notice] Tensor data for analytic powder averaging has been calculated.\n.Python-[Notice] Using default setting &quot;&quot; for instrument &quot;PANTHER&quot;\nPython-[Notice] Using default setting &quot;&quot; for instrument &quot;PANTHER&quot;\nPython-[Notice] Data not found in cache. Structure factors need to be calculated.\nPython-[Notice] Warning: [Errno 2] Unable to open file (unable to open file: name = &#x27;Si2-sc_CalculateSPowder.hdf5&#x27;, errno = 2, error message = &#x27;No such file or directory&#x27;, flags = 0, o_flags = 0) Data has to be calculated.\nPython-[Notice] Tensor data for analytic powder averaging has been calculated.\n..\n======================================================================\nFAIL: test_1d_order10 (AbinsCalculateSPowderTest.SCalculatorFactoryPowderTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/test/Abins/AbinsCalculateSPowderTest.py&quot;, line 117, in test_1d_order10\n    self._good_case(name=self._si2 + &quot;_1d_o10&quot;, castep_name=self._si2, quantum_order_num=2, autoconvolution=True)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/test/Abins/AbinsCalculateSPowderTest.py&quot;, line 158, in _good_case\n    self._check_data(good_data=good_data[&quot;S&quot;], data=calculated_data.extract())\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/test/Abins/AbinsCalculateSPowderTest.py&quot;, line 228, in _check_data\n    assert_almost_equal(ref, calculated)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/contextlib.py&quot;, line 75, in inner\n    return func(*args, **kwds)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/site-packages/numpy/testing/_private/utils.py&quot;, line 588, in assert_almost_equal\n    return assert_array_almost_equal(actual, desired, decimal, err_msg)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/contextlib.py&quot;, line 75, in inner\n    return func(*args, **kwds)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/site-packages/numpy/testing/_private/utils.py&quot;, line 1099, in assert_array_almost_equal\n    assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/contextlib.py&quot;, line 75, in inner\n    return func(*args, **kwds)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/site-packages/numpy/testing/_private/utils.py&quot;, line 862, in assert_array_compare\n    raise AssertionError(msg)\nAssertionError: \nArrays are not almost equal to 7 decimals\n\nMismatched elements: 656 / 4100 (16%)\nMax absolute difference: 1.23045312e-06\nMax relative difference: 15.78325754\n x: array([5.7885427e-26, 6.7769479e-26, 4.1057139e-26, ..., 0.0000000e+00,\n       0.0000000e+00, 0.0000000e+00])\n y: array([2.4720980e-25, 2.7153057e-25, 2.1862108e-25, ..., 0.0000000e+00,\n       0.0000000e+00, 0.0000000e+00])\n\n----------------------------------------------------------------------\nRan 6 tests in 5.147s\n\nFAILED (failures=1)\n\n          Start 1876: MDAlgorithmsTest_Integrate3DEventsTest\n"
            }
        }
    ]
}